/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my_package;

import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author hugob
 */


public class FluxInterface extends javax.swing.JFrame {

     
     NouvellesControleur controleur;
     Timer timer;

    /**
     * Creates new form NewJFrame
     * @param controleur
     */
    public FluxInterface(NouvellesControleur controleur) {
        
           /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FluxInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FluxInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FluxInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FluxInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>   
        timer = new Timer();
        this.controleur = controleur;
        initComponents();
        initialiserNouvelles();
    }
    
     /**
     * Creer la table
     */   
    AbstractTableModel model = new AbstractTableModel() {

            @Override
            public String getColumnName(int column) {
                if(column == 0) {
                    return "Titre";
                } else if(column == 1) {
                    return "Description";
                } else if(column == 2) {
                     return "Lien";
                } else {
                    return "Date de publication";
                }
            }
            
            @Override
             public int getRowCount() {
               return controleur.getListeNouvelle().size();
            }

            @Override
            public int getColumnCount() {
                return 4;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                
                if(columnIndex == 0) {
                    return controleur.getListeNouvelle().get(rowIndex).getTitle();
                } else if(columnIndex == 1) {
                    return controleur.getListeNouvelle().get(rowIndex).getDescription();
                } else if(columnIndex == 2) {
                     return controleur.getListeNouvelle().get(rowIndex).getLink();
                } else {
                    return controleur.getListeNouvelle().get(rowIndex).getPubDate();
                }
                
                
            }
    };
    
    /*
    Description :
    Mettre a jour la table d'evenements
    */
    public void mettreAJourListing() {
        NouvelleTable.updateUI(); 
        setNombreNouvelle();
    }
    /*
    Description :
    Mettre a jour la table d'evenements
    */
    public void afficherMessage(String message) {
        Messages.setText(message);
        supprimerMesage();
    }
    
    
    public void supprimerMesage() 
    {  
        new java.util.Timer().schedule( 
                new java.util.TimerTask() {
                    @Override
                    public void run() {
                        // your code here
                        Messages.setText("");
                    }
                }, 
                5000 
        );
    } 
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        ajoutBouton = new javax.swing.JButton();
        exporterBouton = new javax.swing.JButton();
        enregisterBouton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Messages = new javax.swing.JTextPane();
        label1 = new java.awt.Label();
        nombreLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        NouvelleTable = new javax.swing.JTable();
        descLabel = new javax.swing.JLabel();
        Info = new java.awt.Label();

        jMenu1.setText("jMenu1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel1.setText("Ajouter un évènement");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel1)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        ajoutBouton.setBackground(new java.awt.Color(16, 113, 20));
        ajoutBouton.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        ajoutBouton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my_package/add-2.png"))); // NOI18N
        ajoutBouton.setText("Ajouter un évènement");
        ajoutBouton.setToolTipText("Ajouter un évènement");
        ajoutBouton.setActionCommand("ajout");
        ajoutBouton.setAutoscrolls(true);
        ajoutBouton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.green, null));
        ajoutBouton.setHideActionText(true);
        ajoutBouton.setIconTextGap(10);
        ajoutBouton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajoutBoutonMouseClicked(evt);
            }
        });
        ajoutBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutBoutonActionPerformed(evt);
            }
        });

        exporterBouton.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        exporterBouton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my_package/export.png"))); // NOI18N
        exporterBouton.setText("Exporter");
        exporterBouton.setIconTextGap(10);
        exporterBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exporterBoutonActionPerformed(evt);
            }
        });

        enregisterBouton.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        enregisterBouton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my_package/disk.png"))); // NOI18N
        enregisterBouton.setText("Enregistrer");
        enregisterBouton.setIconTextGap(10);
        enregisterBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregisterBoutonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Trier par : ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", "Pertinence", "" }));

        Messages.setEditable(false);
        Messages.setBackground(new java.awt.Color(204, 204, 204));
        Messages.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        Messages.setAutoscrolls(false);
        Messages.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Messages.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Messages.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Messages.setEnabled(false);
        Messages.setRequestFocusEnabled(false);
        Messages.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        Messages.setVerifyInputWhenFocusTarget(false);
        jScrollPane3.setViewportView(Messages);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(exporterBouton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(enregisterBouton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ajoutBouton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ajoutBouton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(enregisterBouton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exporterBouton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(13, 25, 13));
        label1.setText("Flux de nouvelles de la TELUQ");

        nombreLabel.setText("Nombre");

        NouvelleTable.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        NouvelleTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NouvelleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Description", "Lien", "Date Publication"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        NouvelleTable.setToolTipText("Cliquer pour modifier la nouvelle");
        NouvelleTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        NouvelleTable.setGridColor(new java.awt.Color(153, 153, 153));
        NouvelleTable.setName("tableNouvelles"); // NOI18N
        NouvelleTable.setRowHeight(40);
        NouvelleTable.setRowMargin(2);
        NouvelleTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NouvelleTableFocusGained(evt);
            }
        });
        NouvelleTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NouvelleTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(NouvelleTable);

        descLabel.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        descLabel.setForeground(new java.awt.Color(136, 140, 144));
        descLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descLabel.setText("descLabel");
        descLabel.setToolTipText("");

        Info.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Info.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        Info.setText("Cliquer sur une nouvelle pour la modifier");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(descLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreLabel)
                    .addComponent(Info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        label1.getAccessibleContext().setAccessibleName("title");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void ajoutBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutBoutonActionPerformed
        // TODO add your handling code here:
  
    }//GEN-LAST:event_ajoutBoutonActionPerformed
    
    private void initialiserNouvelles(){
       setNombreNouvelle();
       label1.setText(controleur.getTitle());
       descLabel.setText(controleur.getDescription());
       NouvelleTable.setModel(model);
    }
    
    private void setNombreNouvelle(){
        int nbRows = controleur.getListeNouvelle().size();
       nombreLabel.setText("Total :" + Integer.toString(nbRows));
    }

    private void exporterBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exporterBoutonActionPerformed
        // TODO add your handling code here:
        controleur.afficherExport();
    }//GEN-LAST:event_exporterBoutonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ajoutBoutonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutBoutonMouseClicked
        // TODO add your handling code here:
       controleur.afficherAjout();
   //  controleur.afficherEdit(0);
       
    }//GEN-LAST:event_ajoutBoutonMouseClicked

   // Description : Faire apparaitre la fenetre de modification
   // 
    private void NouvelleTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NouvelleTableMouseClicked
        // TODO add your handling code here:
       int r = NouvelleTable.rowAtPoint(evt.getPoint());
       if (r >= 0 && r < NouvelleTable.getRowCount()) {
          NouvelleTable.setRowSelectionInterval(r, r);
          controleur.afficherEdit(r);
        } else {
            NouvelleTable.clearSelection();
        }
    }//GEN-LAST:event_NouvelleTableMouseClicked

    private void enregisterBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregisterBoutonActionPerformed

          String message = "Enregistrer...";
          controleur.afficherMessage(message);
    }//GEN-LAST:event_enregisterBoutonActionPerformed

    private void NouvelleTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NouvelleTableFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_NouvelleTableFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Info;
    private javax.swing.JTextPane Messages;
    private javax.swing.JTable NouvelleTable;
    private javax.swing.JButton ajoutBouton;
    private javax.swing.JLabel descLabel;
    private javax.swing.JButton enregisterBouton;
    private javax.swing.JButton exporterBouton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable6;
    private java.awt.Label label1;
    private javax.swing.JLabel nombreLabel;
    // End of variables declaration//GEN-END:variables

    private void FeedControleur() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    
}
